version: "3.9"
services:

  redis:
    image: redis:6.2.6
    ports:
      - "127.0.0.1:6379:6379"

  backend:
    extends:
      file: ./services/backend.yml
      service: backend
    depends_on:
      - redis
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://api-node.testnet1.nonprod.fhe.zone:7747
      ETHEREUM_JSONRPC_TRACE_URL: http://api-node.testnet1.nonprod.fhe.zone:7747
        #ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8548/
      DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      CHAIN_ID: '42069'
    ports:
      - "0.0.0.0:4000:4000"

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  stats:
    extends:
      file: ./services/stats.yml
      service: stats
    depends_on:
      - backend
    environment:
      STATS__BLOCKSCOUT_DB_URL: postgresql://postgres:@postgres:5432/blockscout
      STATS__DB_URL: postgresql://postgres:@postgres:5432/stats
      STATS__CREATE_DATABASE: true
      STATS__RUN_MIGRATIONS: true
      STATS__FORCE_UPDATE_ON_START: true