version: '3.9'

services:
  stats:
    image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-latest}
    platform: linux/amd64
    restart: always
    container_name: 'stats'
    entrypoint:
     - /bin/sh
     - -c
     - |
         echo "sleep for 14sec"
         sleep 14 
         /app/stats-server
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-stats.env
